# EAS Build and GitHub Release Workflow
name: EAS Build and Release

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - android
          - ios

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build Android APK
        if: github.event.inputs.platform == 'android' || github.event.inputs.platform == 'all' || startsWith(github.ref, 'refs/tags/')
        run: eas build --platform android --profile production --non-interactive --no-wait
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build Android AAB
        if: startsWith(github.ref, 'refs/tags/')
        run: eas build --platform android --profile production-aab --non-interactive --no-wait
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build iOS
        if: github.event.inputs.platform == 'ios' || github.event.inputs.platform == 'all' || startsWith(github.ref, 'refs/tags/')
        run: eas build --platform ios --profile production --non-interactive --no-wait
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Download Build Artifacts
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          # Wait for builds to complete and download
          sleep 300  # Wait 5 minutes for builds to start
          # Add logic to download completed builds

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ## HealthTech Mobile App Release
            
            ### Downloads
            - Android APK: Available in release assets
            - Android AAB: Available in release assets  
            - iOS IPA: Available in release assets
            
            ### Installation
            **Android**: Download the APK and install directly
            **iOS**: Download IPA and install via TestFlight or enterprise distribution
            
            ### What's New
            Check the release notes below for details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  submit-stores:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Submit to Google Play
        run: eas submit --platform android --latest --profile production
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Submit to App Store
        run: eas submit --platform ios --latest --profile production
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
